---
Name: redirectedurls
After:
  - 'framework/*'
  - 'cms/*'
---
RequestHandler:
  extensions:
    - RedirectedURLHandler

ContentController:
  extensions:
    - RedirectedURLHandler

ModelAsController:
  extensions:
    - RedirectedURLHandler
